export const TASK_STATUSES = {
  NOT_STARTED: 'NOT_STARTED',
  ASSIGNED: 'ASSIGNED',
  IN_PROGRESS: 'IN_PROGRESS',
  DELAYED: 'DELAYED',
  INSPECTION_REQUESTED: 'INSPECTION_REQUESTED',
  APPROVED: 'APPROVED',
  REWORK: 'REWORK'
};

export const TASK_PRIORITIES = {
  HIGH: 'HIGH',
  MEDIUM: 'MEDIUM',
  LOW: 'LOW'
};

export const TRADE_TYPES = [
  'BRICK WORK', 'PLASTER WORK', 'POP', 'TILES', 'PLUMBER',
  'FABRICATION', 'WATERPROOFING', 'ELECTRICAL', 'PAINTING',
  'CARPENTRY', 'FALSE CEILING', 'DOOR FITTING', 'SANITARY', 'CLEANING'
];

export const SKILL_LEVELS = {
  MASON: 'MASON',
  HELPER: 'HELPER',
  LEAD: 'LEAD'
};

export const SNAGGING_STATUSES = {
  OPEN: 'OPEN',
  IN_REPAIR: 'IN_REPAIR',
  FIXED: 'FIXED',
  VERIFIED: 'VERIFIED'
};
